# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3156391a13752d77aec622b969946f947733d947993075f0729c873c6b538cf413611e26f8e7b4f64f34a75cfd9c457673fb469dc5a3ad274d60df46023e477c

test:
  secret_key_base: d2043034240416d573b0d769d1361347bb085ee41bc890478917e1ac4788817819609075d435f92d762faf5fcd6fdb63473b391d114517545743e29f3e23e103

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
